import Head from "next/head";
import Image from "next/image"
import { getProviders, signIn, useSession } from "next-auth/react"
import SpotifyTextLogo from "/public/Spotify-textLogo.jpeg"
import { useRouter } from "next/router";
import { useEffect } from "react";
import Loader from "../../components/Loader";

const SignIn = ({ providers }) => {

    const { data: session } = useSession();
    const router = useRouter();

    useEffect(() => {
        if (session) {
            router.push("/");
        }
    }, [router, session])

    if (session)
        return <Loader />;

    return (
        <div className="flex flex-col justify-center items-center pt-36 space-y-8 " >
            <Head>
                <title>Login - Spotify  </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Image
                src={SpotifyTextLogo}
                alt="logo"
                height={250}
                width={500}
                objectFit="contain"
                className="animate-pulse"
            />

            {Object.values(providers).map((provider) => (
                <div key={provider.id}>
                    <button
                        className="bg-emerald-600 text-slate-200 p-3 rounded-full shadow-lg
                        hover:bg-emerald-500 font-medium uppercase hover:scale-105"
                        onClick={() => signIn(provider.id)}
                    >
                        Sign in with {provider.name}
                    </button>
                </div>
            ))}
        </div>
    )

};

export default SignIn;


export async function getServerSideProps() {
    const providers = await getProviders();
    return {
        props: { providers },
    }

}