import Head from 'next/head'
import { useSession } from "next-auth/react"
import { useRouter } from "next/router"
import Content from '../components/Content'
import Dashboard from '../components/Dashboard'
import Loader from '../components/Loader'


export default function Home() {
  const router = useRouter()
  const { status, data: session } = useSession({
    required: true,
    onUnauthenticated() {
      router.push("/auth/signin")
    }
  })

  if (status === "loading")
    return <Loader />

  return (
    <div >
      <Head>
        <title>r-spotify  </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-full bg-neutral-800">
        <Dashboard />
      </main>
    </div>
  )
}



export async function getStaticProps() {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=10')
  const articles = await res.json()

  return {
    props: {
      articles
    }
  }
}
